cookie:
  expiry_days: 7
  key: 7eb2435ab5352ef6e1cd343d6e302bea55f1fd13948979ded97eedecec62c544
  name: pm_inventory_auth
credentials:
  usernames:
    admin:
      email: admin@company.com
      name: Admin User
      password: $2b$12$mBWAxNxFLRke4i4YVw.4Q.HgRxZ1YB5hoVCioQ8i1elppBN.EnLTm
      role: admin
    jitesh_patil:
      email: jitesh.patil@mosaicwellness.in
      name: Jitesh
      password: $2b$12$mBWAxNxFLRke4i4YVw.4Q.HgRxZ1YB5hoVCioQ8i1elppBN.EnLTm
      role: manager
    manager:
      email: manager@company.com
      name: Inventory Manager
      password: $2b$12$mBWAxNxFLRke4i4YVw.4Q.HgRxZ1YB5hoVCioQ8i1elppBN.EnLTm
      role: manager
    viewer:
      email: viewer@company.com
      name: Dashboard Viewer
      password: $2b$12$mBWAxNxFLRke4i4YVw.4Q.HgRxZ1YB5hoVCioQ8i1elppBN.EnLTm
      role: viewer
